name: CI/CD

on:
  push:
    branches:
      - master
env:
  APPLICATION_NAME: react-hook-form
  IMAGE: dsmercy/react-hook-form
  TAG: 1.0.${{ github.run_number }}
  DOCKERFILE_PATH: ""
  NAMESPACE: development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:${{ env.TAG }}

  deploy-secrets:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Deploy secrets to Kubernetes
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          namespace: ${{ env.NAMESPACE }}
        env:
          MY_CONNECTION_STRING: ${{ secrets.MY_CONNECTION_STRING }}

  deploy-app:
    runs-on: ubuntu-latest
    needs: deploy-secrets
    steps:
      - name: Set up Kubernetes cluster
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          namespace: ${{ env.NAMESPACE }}
        # env:
        #   KUBECONFIG: ${{ secrets.KUBECONFIG }}
        #   NAMESPACE: ${{ env.NAMESPACE }}
      - name: Deploy to Kubernetes
        run: |
          echo "ls ../"
          ls ../
          echo "ls ../react-hook-form"
          ls ../react-hook-form
      - name: Deploy to Kubernetes using Helm
        uses: Azure/k8s-deploy@v1
        with:
          namespace: ${{ env.NAMESPACE }}
          manifests: ../react-hook-form/.
          helm-chart: ../react-hook-form/.
          helm-release: ${{ env.APPLICATION_NAME }}
          helm-arguments: '--set image.repository=${{ env.IMAGE }},image.tag=${{ env.TAG }},namespace=${{ env.NAMESPACE }}'
          kubectl-version: 'latest'
          # helm upgrade --install ${{ env.APPLICATION_NAME }} ../react-hook-form/. --namespace ${{ env.NAMESPACE }} \
          #   --set image.repository=${{ env.IMAGE }} \
          #   --set image.tag=${{ env.TAG }} \
          #   --set namespace=${{ env.NAMESPACE }}
